### ISSUE TITLE
React & web component: Masthead - when user changes Orientation from portrait to landscape view, the page is not loading properly.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5192]
## Detailed description

On iPhone, iOS 14
Issue:
Once the hamburger opened, when we change Orientation from portrait to landscape view, the page is not loading properly.

Note: It is working fine once we refresh the page

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7d3ab4b1-2b1f-43ac-a5a2-6d53793f56df)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6ac05ea5-03a8-46a4-8dac-2d6e92024ede)

**Comment by ariellalgilmore** [comment]
@Praveen-sr looks like this has been fixed. Can you re-test to make sure?

**Comment by Praveen-sr** [comment]
@IgnacioBecerra @ariellalgilmore  I re tested this on staging, I still see the same issue on landscape mode.

React:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/992cfb34-349c-4bca-94c5-4f7499b52b38)

Web component:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/2be5e85c-0b8f-4f86-b125-bf6084a07906)

**Comment by RobertaJHahn** [comment]
@jeffchew @ljcarot I thought that we removed testing of landscape mode from the Prod QA testing scope.

**Comment by IgnacioBecerra** [comment]
After attempting to replicate this issue on an actual iPhone 8 and iPhone X, as well as emulating the latest model and iOS, this bug wasn't able to be replicated.

After discussion with the team, due to this bug being a specific edge case where this is only seen in few devices, we've decided to close this issue.

cc: @RobertaJHahn
