### ISSUE TITLE
[Link List] React:  default mobile & end of section: Arrow alignment bug

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#6874]
## Detailed description

The Link List using ~web components~ React (WC is fixed now. Still an issue in React) has an issue in Mobile view. If the text for a link is too long, the link icon's margin increases to center it for the item. However, if another item in the link list is only on a single line, its own link icon is no longer aligned with it.

![image](https://user-images.githubusercontent.com/47429622/129236998-52c96438-e9f1-45e2-95c1-2459580a0b08.png)

## Steps to reproduce the issue

1. Go to https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-link-list--default
2. Inspect and toggle device toolbar to view as mobile
3. Update the first link to have more text so that it takes up two lines
4. The icon no longer lines up with the single-line link.

**Comment by shixiedesign** [comment]
This is a bug I've noticed as well. https://www.ibm.com/standards/carbon/web-components/?path=/story/components-link-list--end-of-section 

Expected behavior is **arrows will align to first line of text**:

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b0befb59-b7cd-4fcf-beb0-01b8b314caeb)

**Comment by EAVilleda** [comment]
@shixiedesign I just want to point out that the link list shown in my screenshot is the link list default, not end of section.

**Comment by RobertaJHahn** [comment]
@photodow Can you investigate this?

**Comment by RobertaJHahn** [comment]
Copy of Aug 17 Slack conversation:  ![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/f7698184-1f12-4fc1-9340-44244dcd1bd9)

cc:  @photodow

**Comment by andy-blum** [comment]
@shixiedesign & @jeffchew was this issue fixed with #6910?

**Comment by shixiedesign** [comment]
@andy-blum this is still an issue in React, I believe we accidentally added the wrong label. 
![image](https://user-images.githubusercontent.com/15144993/135864982-1654a764-005a-48f1-a900-afe755fc580d.png)
