### ISSUE TITLE
[Content Block Horizontal]: Bottom Padding is not 160px

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7745]
### Description

The dds-content-group-horizontal needs 160px bottom padding in desktop view, 96px in tablet view, and 64px in mobile view. Specifically this seems to be coming from a margin-top above the horizontal rule, though we need the spacing in between the content and horizontal rule to be 160px. 

![image](https://user-images.githubusercontent.com/47429622/143086503-486cdabb-1970-4222-adb9-711a8ad16c6c.png)

### Component(s) impacted

Content Group Horizontal. I'm unable to find the storybook page for it and the link we have is outdated. Was this replaced by Content Block Horizontal? 

### Carbon for IBM.com version

v1.26.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

No codesandbox avaiable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@EAVilleda correct, the component has been renamed to `[content-block-horizontal](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-content-block-horizontal--default)` and the spacing issues have been fixed.

**Comment by druckerk** [comment]
@jeffchew - Can we reopen this ticket. The renamed content-block-horizontal component margin-top set for the dds-hr tag is still not set correctly. The margin-top for the dds-hr tag is currently set to 32 px for sm, 48 px for md, and 96 px for lg and greater. The dss-hr tag needs to have margin-top set to 64 px for sm, 96 px for md, and 160 px for lg and greater.

CC: @EAVilleda , @kennylam

**Comment by druckerk** [comment]
Below are the screenshots showing the padding needed with the <dds-hr> and with <dds-hr> removed. 

**Component with <dds-hr>:**
breakpoint sm - 
<img width="498" alt="dds-content-block-horizontal_padding_with_dds-hr_breakpoint-sm" src="https://user-images.githubusercontent.com/88403358/153247523-2e1f79f5-79d6-4909-b688-2df7db1b00af.png">

breakpoint md - 
<img width="659" alt="dds-content-block-horizontal_padding_with_dds-hr_breakpoint-md" src="https://user-images.githubusercontent.com/88403358/153247628-06f0eecc-4958-479c-9383-585e2785cf0c.png">

breakpoint lg and greater - 
<img width="1049" alt="dds-content-block-horizontal_padding_with_dds-hr_breakpoint-lg-and-greater" src="https://user-images.githubusercontent.com/88403358/153247696-e0c3f007-eab1-46f5-bc88-de5530c950b9.png">

**Component with <dds-hr> removed:** 
breakpoint sm - 
<img width="500" alt="dds-content-block-horizontal_padding_with_dds-hr_removed_breakpoint-sm" src="https://user-images.githubusercontent.com/88403358/153247851-2dabc522-dd3b-4cdc-ad79-efd33c08d267.png">

breakpoint md - 
<img width="667" alt="dds-content-block-horizontal_padding_with_dds-hr_removed_breakpoint-md" src="https://user-images.githubusercontent.com/88403358/153247950-985ddb2e-faaf-4a38-93b1-ae075ffaf442.png">

breakpoint lg and greater - 
<img width="1046" alt="dds-content-block-horizontal_padding_with_dds-hr_removed_breakpoint-lg-greater" src="https://user-images.githubusercontent.com/88403358/153248027-fb23ccbd-e965-498c-9fad-9e9439810fce.png">

Let me know if you have any questions.

**Comment by oliviaflory** [comment]
Moving to backlog while we work out the spacing requirements for all content blocks, groups and items.
